server:
  port: 8083
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      bootstrap-servers: localhost:29092
      properties:
        spring.json.trusted.packages: com.investments.matchingservice
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.investments.matchingservice.domain.api.event.Event
      auto-offset-reset: latest